name: pipeline
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      Deploy:
        description: 'Deploy or destroy composer RC1 (Select "true" to Deploy)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      Destroy:
        description: 'Destroy or destroy composer RC1 (Select "true" to Destroy)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'       

jobs:
  deploy-to-rc:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'write'
      id-token: 'write'
      pull-requests: 'write'

    steps:
    - name: Choice
      id: choice
      run: |
        set -e
        if [[ ${{ github.event.inputs.Deploy }} == 'true' ]]; then
          Deploy=true
        else
          Deploy=false
        fi

        if [[ ${{ github.event.inputs.Destroy }} == 'true' ]]; then
          Destroy=true
        else
          Destroy=false
        fi
    
    - name: Deploy
      id: test1
      if: $Deploy == 'true' 
      run: |
        set -e
        echo "Deploy"

    - name: Destroy
      id: test2
      if: $Destroy == 'true'
      run: |
        set -e
        echo "Destroy"
